# Generated by Django 5.0.7 on 2025-02-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rr', '0002_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
