# Generated by Django 5.0.7 on 2025-02-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rr', '0004_remove_order_quantity_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='not_available',
            field=models.BooleanField(default=False),
        ),
    ]
