# Generated by Django 5.0.7 on 2025-02-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rr', '0006_alter_menuitem_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
